image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy

variables:
  project: Bubbio

before_script:
  - dotnet restore $project

build:
  stage: build
  script:
    - bash scripts/build.sh

test:
  stage: test
  services:
    - name: mongo:latest
      alias: localhost
  script:
    - bash scripts/test.sh